services:
  mongodb:
      image: mongo:7.0.12
      container_name: mongodb
      env_file:
        - .env
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      ports:
        - "27017:27017"
      volumes:
        - ./mongo/mongod.conf:/etc/mongod.conf
        - ./volumes/mongo_data:/data/db
        - ./volumes/logs/mongo_logs:/var/log/mongodb
      command: [ "mongod", "--config", "/etc/mongod.conf" ]


  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./volumes/logs/fastapi_logs:/hh/volumes/logs/fastapi_log
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-config app/core/log_config.yml
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

