services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongo_data:/data/db
      - ./volumes/logs/mongo_logs:/var/log/mongodb
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    restart: always
    entrypoint: sh -c "mkdir -p /var/log/mongodb && chmod -R 777 /var/log/mongodb && mongod --config /etc/mongod.conf"


  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./volumes/logs/fastapi_logs:/hh/volumes/logs/fastapi_log
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-config app/core/log_config.yml
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongodb

