version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: 'volumes/logs/fastapi_log/fastapi.log'
loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: False
  uvicorn.error:
    handlers: [console, file]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: False
root:
  level: INFO
  handlers: [console, file]
